# This file was generated by GoReleaser. DO NOT EDIT.
cask "dosu" do
  name "dosu"
  desc "Dosu CLI tool"
  homepage "https://github.com/dosu-ai/dosu-cli"
  version "0.0.1-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dosu"

  on_macos do
    on_intel do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Darwin_x86_64.tar.gz"
      sha256 "60cf2823b9b06e79e7e62f154cfd9b7078ecaec8a0ee17a58b1e91229c244fd5"
    end
    on_arm do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Darwin_arm64.tar.gz"
      sha256 "6a14a89d2cf30068ecb6e0e0c00f37d92dcf0fad7193a18fd7bb2cf24ec4c251"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Linux_x86_64.tar.gz"
      sha256 "7acfcbe7061509ccaef1ac6e2438380e8bb0d27fbcd7160161224108a76ea170"
    end
    on_arm do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Linux_arm64.tar.gz"
      sha256 "e51baf4cec15499e7c1379e7cb3f0d304178782a43ec1181185239333faa027b"
    end
  end

  # No zap stanza required
end
