#!/bin/bash
set -e

# Update Homebrew formula with new version and checksums
# Usage: ./scripts/update-formula.sh <version>
# Example: ./scripts/update-formula.sh 0.0.2-alpha

VERSION="${1}"

if [[ -z "${VERSION}" ]]
then
  echo "Usage: ${0} <version>"
  echo "Example: ${0} 0.1.0"
  exit 1
fi

# Strip 'v' prefix if provided
VERSION="${VERSION#v}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "${SCRIPT_DIR}")"
FORMULA_FILE="${REPO_DIR}/Formula/dosu.rb"
BASE_URL="https://github.com/dosu-ai/dosu-cli/releases/download/v${VERSION}"

echo "Updating formula to version ${VERSION}..."

# Fetch the checksums.txt file generated by goreleaser
CHECKSUMS_URL="${BASE_URL}/checksums.txt"
echo "Fetching checksums from: ${CHECKSUMS_URL}"

CHECKSUMS=$(curl -sfL "${CHECKSUMS_URL}" || true)
if [[ -z "${CHECKSUMS}" ]]
then
  echo "Error: Could not fetch checksums.txt from release v${VERSION}"
  echo "Make sure the release exists at: ${BASE_URL}"
  exit 1
fi

# Parse checksums from the goreleaser checksums.txt file
# Format: <sha256>  <filename>
DARWIN_X86=$(echo "${CHECKSUMS}" | grep "dosu_Darwin_x86_64.tar.gz" | awk '{print $1}' || true)
DARWIN_ARM=$(echo "${CHECKSUMS}" | grep "dosu_Darwin_arm64.tar.gz" | awk '{print $1}' || true)
LINUX_X86=$(echo "${CHECKSUMS}" | grep "dosu_Linux_x86_64.tar.gz" | awk '{print $1}' || true)
LINUX_ARM=$(echo "${CHECKSUMS}" | grep "dosu_Linux_arm64.tar.gz" | awk '{print $1}' || true)

# Validate we got all checksums
if [[ -z "${DARWIN_X86}" ]]
then
  echo "Error: Could not find checksum for dosu_Darwin_x86_64.tar.gz"
  exit 1
fi
if [[ -z "${DARWIN_ARM}" ]]
then
  echo "Error: Could not find checksum for dosu_Darwin_arm64.tar.gz"
  exit 1
fi
if [[ -z "${LINUX_X86}" ]]
then
  echo "Error: Could not find checksum for dosu_Linux_x86_64.tar.gz"
  exit 1
fi
if [[ -z "${LINUX_ARM}" ]]
then
  echo "Error: Could not find checksum for dosu_Linux_arm64.tar.gz"
  exit 1
fi

echo "Checksums found:"
echo "  Darwin x86_64: ${DARWIN_X86}"
echo "  Darwin arm64:  ${DARWIN_ARM}"
echo "  Linux x86_64:  ${LINUX_X86}"
echo "  Linux arm64:   ${LINUX_ARM}"

echo "Updating formula file..."

cat >"${FORMULA_FILE}" <<EOF
# typed: false
# frozen_string_literal: true

class Dosu < Formula
  desc "CLI tool for Dosu"
  homepage "https://github.com/dosu-ai/dosu-cli"
  version "${VERSION}"

  on_macos do
    on_intel do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Darwin_x86_64.tar.gz"
      sha256 "${DARWIN_X86}"
    end
    on_arm do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Linux_x86_64.tar.gz"
      sha256 "${LINUX_X86}"
    end
    on_arm do
      url "https://github.com/dosu-ai/dosu-cli/releases/download/v#{version}/dosu_Linux_arm64.tar.gz"
      sha256 "${LINUX_ARM}"
    end
  end

  def install
    bin.install "dosu"
  end

  def post_install
    return unless OS.mac?

    ohai "Removing quarantine attribute..."
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{bin}/dosu"
  end

  test do
    system "#{bin}/dosu", "--version"
  end
end
EOF

echo ""
echo "Formula updated successfully!"
echo ""
echo "Next steps:"
echo "  cd ${REPO_DIR}"
echo "  git add Formula/dosu.rb"
echo "  git commit -m 'Update dosu to v${VERSION}'"
echo "  git push"
